apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webapp-dev

resources:
  - ../../base

patches:
  - path: ingress-patch.yaml
  - path: ui-config-patch.yaml

images:
  - name: ghcr.io/ronelleti/webapp-api
    newTag: dev
  - name: ghcr.io/ronelleti/webapp-ui
    newTag: dev
  - name: ghcr.io/ronelleti/webapp-db
    newTag: dev

replicas:
  - name: api
    count: 1
  - name: ui
    count: 1
