apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservice-prod

resources:
  - ../../base

replicas:
  - name: microservice
    count: 3

images:
  - name: ghcr.io/your-org/gitops-microservice-platform
    newTag: stable
